blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/renodesper/ngopidi/discussions
    about: Please use discussions for general questions or community chat.
